apply plugin: 'com.android.application'

def gitdata = new ByteArrayOutputStream()
// change this line to /* if not using git
exec {
    commandLine "git", "--no-pager", "show", "-s", "--format=from commit %H of %as"
    standardOutput = gitdata;
}
//*/

// Update these three to make new version
def VERSIONCODE = 86
def VERSIONNAME = "2.6.0"
def CHANGESTRING = "Update version for new release"

def CHANGELOGS = "fastlane/metadata/android/en-US/changeLogs/"
def CHANGEFILE = CHANGELOGS + VERSIONCODE + ".txt"
exec {
    commandLine "echo", "${CHANGESTRING.toString()}"
    standardOutput = new FileOutputStream(rootProject.file(CHANGEFILE))
}
exec {
    commandLine "git", "add", "../" + "${CHANGEFILE.toString()}"
}
exec {
    commandLine "sed", "-i", "/This is version/cThis is version " + VERSIONNAME + ".", "../README.md"
}


android {
    compileSdkVersion 29

    defaultConfig {
        applicationId "net.sylvek.itracing2"
        minSdkVersion 22
        //noinspection ExpiredTargetSdkVersion
        targetSdkVersion 29
        versionCode 85
        versionName VERSIONNAME

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    signingConfigs {
        release {
            if (project.hasProperty("keyStore") && project.hasProperty("password")) {
                storeFile file(project.keyStore)
                storePassword project.password
                keyAlias "android"
                keyPassword project.password
            }
        }
    }
    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.debug
            delete("build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml")
            resValue("string", 'build_time', "${(new Date()).toString()}")
            resValue("string", 'build_git', "${gitdata.toString()}")
            jniDebuggable true
            renderscriptDebuggable true
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            delete("build/intermediates/incremental/mergeReleaseResources/merger.xml")
            resValue("string", 'build_time', "${(new Date()).toString()}")
            resValue("string", 'build_git', "${gitdata.toString()}")
        }
    }
}

repositories {
    maven {
        url "https://maven.google.com/"
    }
}

dependencies {
    //noinspection GradleCompatible,GradleCompatible
    api 'com.android.support:appcompat-v7:28.0.0'
    //noinspection GradleCompatible
    api 'com.android.support:support-v13:28.0.0'
    //noinspection GradleCompatible
    api 'com.android.support:design:28.0.0'
    api 'com.android.support:support-annotations:28.0.0'
    api 'org.eclipse.paho:org.eclipse.paho.client.mqttv3:1.1.0'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'tools.fastlane:screengrab:1.0.2'
}
